### ISSUE TITLE
🐛 Bug Report: Document is not defined

### ISSUE THREAD

**Issue by jlsnow301** [alex-grover/astro-themes#10]
**Describe the bug**
Unable to detect the current theme as indicated in the readme, attempting to do so causes ```document is not defined```

**To Reproduce**

1. ```yarn create astro```
2. ```cd [folder]```
3. ```yarn add astro-themes```
4. Attempt to save the theme in memory ```const theme =
  document.documentElement.attributes.getNamedItem("data-theme").value;```

**Expected behavior**
theme = "light" | "dark"

**Screenshots**
![Screenshot 2022-09-14 143202](https://user-images.githubusercontent.com/42397676/190267467-278af156-ed31-4a1d-a087-7f5d5d13491e.png)

**Desktop (please complete the following information):**

- OS: Win11
- Browser Brave
- Version 1.43.89

**Additional context**
Here is the code used to produce the above error https://github.com/jlsnow301/themes-test

**Comment by alex-grover** [comment]
Thanks for the report! The issue here is that the code inside the `---` runs on the server, at build time. So the error itself is because the code isn't running in the browser and as such there's no `document`, or theme at all.

 Try putting that line of code inside a `<script>` tag in the HTML and let me know if that works for your use case!

**Comment by jlsnow301** [comment]
done! thanks for the help. using it as an inline script worked. for ref, this was how I made a theme switch: 
```  
<div class="flex justify-end border-t p-4 theme">
    <script is:inline>
      var lightMode =
        document.documentElement.attributes.getNamedItem("data-theme")
          ?.value === "light";
      function toggleTheme() {
        if (lightMode) {
          document.documentElement.setAttribute("data-theme", "dark");
        } else {
          document.documentElement.setAttribute("data-theme", "light");
        }
        lightMode = !lightMode;
      }
    </script>
    <button
      class="bg-indigo-600 border rounded-full h-8 p-1.5 w-8 text-white icon"
      onclick="toggleTheme()"
    >
      <Icon name="carbon:sun" />
    </button>
  </div>
```

**Comment by jlsnow301** [comment]
Oh! That was actually a github copilot line, I didn't even look to compare it. Good catch.
