### ISSUE TITLE
🐛 Bug Report: conflict with Astro View Transitions

### ISSUE THREAD

**Issue by VictorienDruon** [alex-grover/astro-themes#23]
**Describe the bug**
The selected theme is not saved when changing pages with Astro View Transitions.

**To Reproduce**

1. Create a repo with 2 pages and a shared layout with <Themes /> and <ViewTransitions />
2. Set the theme to something different than the default
3. Navigate between the 2 pages - the theme should go back to the default

**Expected behavior**
The theme should stayed the same when changing pages.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: both chrome and safari
- Version: "astro": "^4.1.2", "astro-themes": "^0.2.4"

**Comment by alex-grover** [comment]
Fixed in 0.2.5! Thank you for reporting!
